import { defineType, defineField } from "sanity";

export default defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  fields: [
    defineField({
      name: "common",
      title: "Common Labels",
      type: "object",
      fields: [
        { name: "viewSpecs", type: "string", title: "View Specs Button" },
        { name: "addToEnquiry", type: "string", title: "Add to Enquiry Button" },
        { name: "readMore", type: "string", title: "Read More Button" },
      ],
    }),
    defineField({
      name: "forms",
      title: "Form Labels",
      type: "object",
      fields: [
        { name: "nameLabel", type: "string", title: "Name Label" },
        { name: "emailLabel", type: "string", title: "Email Label" },
        { name: "phoneLabel", type: "string", title: "Phone Label" },
        { name: "messageLabel", type: "string", title: "Message Label" },
        { name: "companyLabel", type: "string", title: "Company Label" },
        { name: "roleLabel", type: "string", title: "Role Label" },
        { name: "countryLabel", type: "string", title: "Country Label" },
        { name: "productInterestLabel", type: "string", title: "Product Interest Label" },
        { name: "quantityLabel", type: "string", title: "Quantity Label" },
        { name: "tradeQuantityPlaceholder", type: "string", title: "Trade Quantity Placeholder" },
        { name: "submitButton", type: "string", title: "Submit Button" },
        { name: "submittingButton", type: "string", title: "Submitting Button" },
        { name: "successMessage", type: "string", title: "Success Message" },
        { name: "errorMessage", type: "string", title: "Error Message" },
        { name: "requiredIndicator", type: "string", title: "Required Field Indicator" },
        { name: "honeypotTabIndex", type: "number", title: "Honeypot Tab Index" },
        { name: "generalEnquiryEndpoint", type: "string", title: "General Enquiry API Endpoint" },
        { name: "tradeEnquiryEndpoint", type: "string", title: "Trade Enquiry API Endpoint" },
        { name: "sampleRequestMessage", type: "string", title: "Sample Request Message Template" },
        { name: "enquiryListIntro", type: "string", title: "Enquiry List Introduction" },
        { name: "populateEventName", type: "string", title: "Populate Form Event Name" },
        { name: "defaultTab", type: "string", title: "Default Contact Form Tab" },
        { name: "tabValueGeneral", type: "string", title: "Tab Value: General" },
        { name: "tabValueTrade", type: "string", title: "Tab Value: Trade" },
      ],
    }),
    defineField({
      name: "productCard",
      title: "Product Card Settings",
      type: "object",
      fields: [{ name: "placeholderText", type: "string", title: "Placeholder Text" }],
    }),
    defineField({
      name: "productModal",
      title: "Product Modal Settings",
      type: "object",
      fields: [
        { name: "closeAria", type: "string", title: "Close Button Aria Label" },
        { name: "placeholder", type: "string", title: "Media Placeholder" },
        { name: "addToEnquiry", type: "string", title: "Add to Enquiry Button" },
        { name: "requestSample", type: "string", title: "Request Sample Button" },
      ],
    }),
    defineField({
      name: "productDetail",
      title: "Product Detail Settings",
      type: "object",
      fields: [
        { name: "addToEnquiry", type: "string", title: "Add to Enquiry Button" },
        { name: "requestSample", type: "string", title: "Request Sample Button" },
        { name: "backToProducts", type: "string", title: "Back to Products Link" },
        { name: "heroPlaceholder", type: "string", title: "Hero Placeholder Text" },
        { name: "programSuffix", type: "string", title: "Program Suffix" },
      ],
    }),
    defineField({
      name: "navigation",
      title: "Navigation Settings",
      type: "object",
      fields: [
        { name: "home", type: "string", title: "Home Link Label" },
        { name: "about", type: "string", title: "About Link Label" },
        { name: "products", type: "string", title: "Products Link Label" },
        { name: "contact", type: "string", title: "Contact Link Label" },
        { name: "productsLabel", type: "string", title: "Products Dropdown Label" },
        { name: "homeUrl", type: "string", title: "Home URL" },
        { name: "aboutUrl", type: "string", title: "About URL" },
        { name: "productsUrl", type: "string", title: "Products URL" },
        { name: "contactUrl", type: "string", title: "Contact URL" },
      ],
    }),
    defineField({
      name: "footer",
      title: "Footer Settings",
      type: "object",
      fields: [
        { name: "companyTitle", type: "string", title: "Company Title" },
        { name: "companyDescription", type: "text", title: "Company Description" },
        { name: "quickLinksTitle", type: "string", title: "Quick Links Title" },
        { name: "productsTitle", type: "string", title: "Products Title" },
        { name: "certificationsTitle", type: "string", title: "Certifications Title" },
        { name: "isoLabel", type: "string", title: "ISO Label" },
        { name: "fssaiLabel", type: "string", title: "FSSAI Label" },
        { name: "copyrightText", type: "string", title: "Copyright Text" },
        { name: "servingText", type: "string", title: "Serving Text" },
        { name: "privacyPolicyText", type: "string", title: "Privacy Policy Text" },
        { name: "privacyNote", type: "string", title: "Privacy Note" },
      ],
    }),
    defineField({
      name: "enquiry",
      title: "Enquiry Settings",
      type: "object",
      fields: [
        { name: "gradeLabel", type: "string", title: "Grade Label" },
        { name: "notesLabel", type: "string", title: "Notes Label" },
        { name: "packFormatLabel", type: "string", title: "Pack Format Label" },
        { name: "quantityLabel", type: "string", title: "Quantity Label" },
        { name: "moqLabel", type: "string", title: "MOQ Label" },
        { name: "emptyStateText", type: "string", title: "Empty State Text" },
        { name: "pdfError", type: "string", title: "PDF Error Message" },
        { name: "emptyEnquiryError", type: "string", title: "Empty Enquiry Error Message" },
        { name: "openBuilderAria", type: "string", title: "Open Builder Aria Label" },
        { name: "gradePlaceholder", type: "string", title: "Grade Placeholder" },
        { name: "packFormatPlaceholder", type: "string", title: "Pack Format Placeholder" },
        { name: "quantityPlaceholder", type: "string", title: "Quantity Placeholder" },
        { name: "notesPlaceholder", type: "string", title: "Notes Placeholder" },
        { name: "saveLabel", type: "string", title: "Save Label" },
        { name: "cancelLabel", type: "string", title: "Cancel Label" },
        { name: "editLabel", type: "string", title: "Edit Label" },
        { name: "removeAriaLabel", type: "string", title: "Remove Item Aria Label" },
        defineField({
          name: "floatingBar",
          title: "Floating Bar Labels",
          type: "object",
          fields: [
            { name: "item", type: "string", title: "Item Label (Singular)" },
            { name: "items", type: "string", title: "Items Label (Plural)" },
            { name: "inYourEnquiry", type: "string", title: "In Your Enquiry Label" },
            { name: "readyToSubmit", type: "string", title: "Ready To Submit Text" },
            { name: "viewEnquiry", type: "string", title: "View Enquiry Button" },
            { name: "submitEnquiry", type: "string", title: "Submit Enquiry Button" },
          ],
        }),
        defineField({
          name: "panel",
          title: "Enquiry Panel Labels",
          type: "object",
          fields: [
            { name: "title", type: "string", title: "Panel Title" },
            { name: "emptyState", type: "string", title: "Empty State Text" },
            { name: "emptyStateSub", type: "string", title: "Empty State Subtext" },
            { name: "exportPdf", type: "string", title: "Export PDF Button" },
            { name: "submitEnquiry", type: "string", title: "Submit Enquiry Button" },
            { name: "clearAll", type: "string", title: "Clear All Button" },
            { name: "confirmClear", type: "string", title: "Confirm Clear Message" },
            { name: "closePanelAria", type: "string", title: "Close Panel Aria Label" },
          ],
        }),
        defineField({
          name: "builder",
          title: "Enquiry Builder Labels",
          type: "object",
          fields: [{ name: "buttonLabel", type: "string", title: "Button Label" }],
        }),
      ],
    }),
    defineField({
      name: "distribution",
      title: "Distribution Settings",
      type: "object",
      fields: [{ name: "heading", type: "string", title: "Heading" }],
    }),
    defineField({
      name: "contact",
      title: "Contact Page Settings",
      type: "object",
      fields: [
        { name: "officeLabel", type: "string", title: "Corporate Office Label" },
        { name: "phoneLabel", type: "string", title: "Phone Label" },
        { name: "emailLabel", type: "string", title: "Email Label" },
      ],
    }),
    defineField({
      name: "organization",
      title: "Organization Structured Data",
      type: "object",
      fields: [
        { name: "name", type: "string", title: "Organization Name" },
        { name: "url", type: "string", title: "Organization URL" },
        { name: "logoUrl", type: "string", title: "Logo URL" },
        { name: "description", type: "text", title: "Organization Description" },
        {
          name: "address",
          type: "object",
          title: "Address",
          fields: [
            { name: "streetAddress", type: "string", title: "Street Address" },
            { name: "addressLocality", type: "string", title: "City" },
            { name: "addressRegion", type: "string", title: "State/Region" },
            { name: "postalCode", type: "string", title: "Postal Code" },
            { name: "addressCountry", type: "string", title: "Country Code (e.g., IN)" },
          ],
        },
        {
          name: "contactPoint",
          type: "object",
          title: "Contact Point",
          fields: [
            { name: "telephone", type: "string", title: "Telephone" },
            { name: "contactType", type: "string", title: "Contact Type (e.g., sales)" },
            { name: "areaServed", type: "string", title: "Area Served (Country Code)" },
            {
              name: "availableLanguage",
              type: "array",
              of: [{ type: "string" }],
              title: "Available Languages",
            },
          ],
        },
      ],
    }),
    defineField({
      name: "seo",
      title: "SEO Settings",
      type: "object",
      fields: [
        { name: "siteUrl", type: "string", title: "Site URL" },
        { name: "htmlLang", type: "string", title: "HTML Language Code" },
        { name: "metaTitle", type: "string", title: "Meta Title" },
        { name: "metaTitleSuffix", type: "string", title: "Meta Title Suffix" },
        { name: "metaDescription", type: "text", title: "Meta Description" },
        { name: "keywords", type: "array", of: [{ type: "string" }], title: "Keywords" },
        { name: "ogType", type: "string", title: "OpenGraph Type" },
        { name: "twitterCardType", type: "string", title: "Twitter Card Type" },
        {
          name: "robots",
          type: "object",
          title: "Robots.txt Configuration",
          fields: [
            { name: "userAgent", type: "string", title: "User Agent" },
            { name: "allowPath", type: "string", title: "Allow Path" },
            { name: "disallowPath", type: "string", title: "Disallow Path" },
            { name: "sitemapPath", type: "string", title: "Sitemap Path" },
          ],
        },
        {
          name: "sitemap",
          type: "object",
          title: "Sitemap Configuration",
          fields: [
            {
              name: "staticPages",
              type: "array",
              title: "Static Pages",
              of: [
                {
                  type: "object",
                  fields: [
                    { name: "path", type: "string", title: "Path" },
                    { name: "changeFrequency", type: "string", title: "Change Frequency" },
                    { name: "priority", type: "number", title: "Priority" },
                  ],
                },
              ],
            },
            {
              name: "productDefaults",
              type: "object",
              title: "Product Page Defaults",
              fields: [
                { name: "changeFrequency", type: "string", title: "Change Frequency" },
                { name: "priority", type: "number", title: "Priority" },
              ],
            },
          ],
        },
      ],
    }),
    defineField({
      name: "whatsapp",
      title: "WhatsApp Settings",
      type: "object",
      fields: [
        {
          name: "phoneNumber",
          type: "string",
          title: "WhatsApp Phone Number (with country code, no +)",
        },
        { name: "messageTemplate", type: "text", title: "Message Template" },
        { name: "buttonLabel", type: "string", title: "Button Label (Aria)" },
      ],
    }),
    defineField({
      name: "heroConfig",
      title: "Hero Slider Configuration",
      type: "object",
      fields: [
        { name: "autoPlayInterval", type: "number", title: "Auto-play Interval (ms)" },
        { name: "slideNumberPadding", type: "string", title: "Slide Number Padding Character" },
      ],
    }),
    defineField({
      name: "accessibility",
      title: "Accessibility Labels",
      type: "object",
      fields: [
        { name: "skipLinkText", type: "string", title: "Skip Link Text" },
        { name: "skipLinkTarget", type: "string", title: "Skip Link Target ID" },
        { name: "heroSectionAria", type: "string", title: "Hero Section Aria Label" },
        { name: "prevSlideAria", type: "string", title: "Previous Slide Aria Label" },
        { name: "nextSlideAria", type: "string", title: "Next Slide Aria Label" },
        { name: "goToSlideAria", type: "string", title: "Go To Slide Aria Label" },
        { name: "closePanelAria", type: "string", title: "Close Panel Aria Label" },
        { name: "closeModalAria", type: "string", title: "Close Modal Aria Label" },
        { name: "themeToggleAria", type: "string", title: "Theme Toggle Aria Label" },
        { name: "socialFacebookAria", type: "string", title: "Facebook Aria Label" },
        { name: "socialTwitterAria", type: "string", title: "Twitter Aria Label" },
        { name: "socialLinkedinAria", type: "string", title: "LinkedIn Aria Label" },
        { name: "socialInstagramAria", type: "string", title: "Instagram Aria Label" },
      ],
    }),
    defineField({
      name: "themeToggle",
      title: "Theme Toggle Settings",
      type: "object",
      fields: [
        { name: "toggleAria", type: "string", title: "Toggle Button Aria Label" },
        { name: "title", type: "string", title: "Panel Title" },
        { name: "modernLabel", type: "string", title: "Modern Theme Label" },
        { name: "feminineLabel", type: "string", title: "Elegant Theme Label" },
      ],
    }),
    defineField({
      name: "error",
      title: "Error Page Settings",
      type: "object",
      fields: [
        { name: "notFoundCode", type: "string", title: "Not Found Code (404)" },
        { name: "notFoundTitle", type: "string", title: "Not Found Title" },
        { name: "notFoundText", type: "string", title: "Not Found Text" },
        { name: "backHomeButton", type: "string", title: "Back Home Button" },
        { name: "genericErrorTitle", type: "string", title: "Generic Error Title" },
        { name: "genericErrorText", type: "string", title: "Generic Error Text" },
        { name: "tryAgainButton", type: "string", title: "Try Again Button" },
      ],
    }),
    defineField({
      name: "emailTemplates",
      title: "Email Template Settings",
      type: "object",
      fields: [
        { name: "fromName", type: "string", title: "Sender Name" },
        { name: "fromEmail", type: "string", title: "Sender Email" },
        { name: "generalSubject", type: "string", title: "General Enquiry Subject" },
        { name: "tradeSubject", type: "string", title: "Trade Enquiry Subject" },
        { name: "newGeneralEnquiryTitle", type: "string", title: "New General Enquiry Title" },
        { name: "newTradeEnquiryTitle", type: "string", title: "New Trade Enquiry Title" },
        { name: "nameLabel", type: "string", title: "Name Label" },
        { name: "emailLabel", type: "string", title: "Email Label" },
        { name: "phoneLabel", type: "string", title: "Phone Label" },
        { name: "messageLabel", type: "string", title: "Message Label" },
        { name: "companyLabel", type: "string", title: "Company Label" },
        { name: "roleLabel", type: "string", title: "Role Label" },
        { name: "countryLabel", type: "string", title: "Country Label" },
        { name: "productsLabel", type: "string", title: "Products Label" },
        { name: "quantityLabel", type: "string", title: "Quantity Label" },
        { name: "naText", type: "string", title: "N/A Text" },
        { name: "noneText", type: "string", title: "None Text" },
      ],
    }),
    defineField({
      name: "apiMessages",
      title: "API Response Messages",
      type: "object",
      fields: [
        { name: "rateLimitError", type: "string", title: "Rate Limit Error" },
        { name: "validationError", type: "string", title: "Validation Error" },
        { name: "serverError", type: "string", title: "Server Error" },
        { name: "enquirySuccess", type: "string", title: "Enquiry Success Message" },
        { name: "pdfGenerationError", type: "string", title: "PDF Generation Error" },
        { name: "pdfGenerationSuccess", type: "string", title: "PDF Generation Success" },
      ],
    }),
    defineField({
      name: "apiConfig",
      title: "API Configuration",
      type: "object",
      fields: [
        { name: "rateLimitMaxRequests", type: "number", title: "Rate Limit Max Requests" },
        { name: "rateLimitWindowMs", type: "number", title: "Rate Limit Window (ms)" },
        { name: "unknownIpLabel", type: "string", title: "Unknown IP Label" },
        { name: "fallbackEmail", type: "string", title: "Fallback Email" },
        { name: "enquiryTypeGeneral", type: "string", title: "Enquiry Type: General" },
        { name: "enquiryTypeTrade", type: "string", title: "Enquiry Type: Trade" },
        { name: "enquiryStatusNew", type: "string", title: "Enquiry Status: New" },
        { name: "listSeparator", type: "string", title: "List Separator" },
        { name: "breadcrumbSeparator", type: "string", title: "Breadcrumb Separator" },
        { name: "enquiryIdPrefix", type: "string", title: "Enquiry ID Prefix" },
        { name: "httpMethodPost", type: "string", title: "HTTP Method: POST" },
        { name: "contentTypeHeader", type: "string", title: "Content-Type Header Name" },
        { name: "contentTypeJson", type: "string", title: "Content-Type: JSON" },
      ],
    }),
    defineField({
      name: "validation",
      title: "Form Validation Settings",
      type: "object",
      fields: [
        { name: "nameMinLength", type: "number", title: "Name Minimum Length" },
        { name: "nameMinError", type: "string", title: "Name Minimum Length Error" },
        { name: "emailInvalidError", type: "string", title: "Invalid Email Error" },
        { name: "messageMinLength", type: "number", title: "Message Minimum Length" },
        { name: "messageMinError", type: "string", title: "Message Minimum Length Error" },
        { name: "companyMinLength", type: "number", title: "Company Name Minimum Length" },
        { name: "companyRequiredError", type: "string", title: "Company Required Error" },
        { name: "phoneMinLength", type: "number", title: "Phone Minimum Length" },
        { name: "phoneRequiredError", type: "string", title: "Phone Required Error" },
        { name: "countryMinLength", type: "number", title: "Country Minimum Length" },
        { name: "countryRequiredError", type: "string", title: "Country Required Error" },
        { name: "honeypotMaxLength", type: "number", title: "Honeypot Max Length" },
      ],
    }),
    defineField({
      name: "routing",
      title: "Routing Configuration",
      type: "object",
      fields: [
        { name: "queryParamType", type: "string", title: "Query Param: Type" },
        { name: "queryParamProduct", type: "string", title: "Query Param: Product" },
        { name: "queryParamAction", type: "string", title: "Query Param: Action" },
        { name: "actionSample", type: "string", title: "Action Value: Sample" },
        { name: "scrollTargetContact", type: "string", title: "Scroll Target: Contact" },
        { name: "productsHash", type: "string", title: "Products Section Hash" },
        { name: "productsSectionId", type: "string", title: "Products Section ID" },
        { name: "aboutSectionId", type: "string", title: "About Section ID" },
        { name: "capabilitiesSectionId", type: "string", title: "Capabilities Section ID" },
        { name: "ctaSectionId", type: "string", title: "CTA Section ID" },
        { name: "heroSectionId", type: "string", title: "Hero Section ID" },
        { name: "processSectionId", type: "string", title: "Process Section ID" },
        { name: "sustainabilitySectionId", type: "string", title: "Sustainability Section ID" },
        { name: "trustSectionId", type: "string", title: "Trust Section ID" },
        { name: "testimonialsSectionId", type: "string", title: "Testimonials Section ID" },
      ],
    }),
    defineField({
      name: "analytics",
      title: "Analytics Configuration",
      type: "object",
      fields: [
        { name: "eventAddToEnquiry", type: "string", title: "Event: Add to Enquiry (DOM)" },
        { name: "eventAddToEnquiryGA", type: "string", title: "Event: Add to Enquiry (GA4)" },
        { name: "eventSampleRequest", type: "string", title: "Event: Sample Request (GA4)" },
        { name: "eventFormSubmission", type: "string", title: "Event: Form Submission (GA4)" },
        { name: "locationProductPage", type: "string", title: "Location: Product Page" },
        { name: "locationModal", type: "string", title: "Location: Modal" },
        { name: "formTypeGeneral", type: "string", title: "Form Type: General Enquiry" },
        { name: "formTypeTrade", type: "string", title: "Form Type: Trade Enquiry" },
        { name: "paramFormType", type: "string", title: "Parameter: Form Type" },
      ],
    }),
    defineField({
      name: "pdfTemplate",
      title: "PDF Template Settings",
      type: "object",
      fields: [
        { name: "companyName", type: "string", title: "Company Name" },
        { name: "title", type: "string", title: "Document Title" },
        { name: "dateLabel", type: "string", title: "Date Label" },
        { name: "referenceLabel", type: "string", title: "Reference ID Label" },
        { name: "referencePrefix", type: "string", title: "Reference ID Prefix" },
        { name: "contactDetailsLabel", type: "string", title: "Contact Details Label" },
        { name: "nameLabel", type: "string", title: "Name Label" },
        { name: "companyLabel", type: "string", title: "Company Label" },
        { name: "emailLabel", type: "string", title: "Email Label" },
        { name: "phoneLabel", type: "string", title: "Phone Label" },
        { name: "indexLabel", type: "string", title: "Index Column Label" },
        { name: "naText", type: "string", title: "N/A Text" },
        { name: "emptyFieldText", type: "string", title: "Empty Field Text" },
        { name: "filenamePrefix", type: "string", title: "Filename Prefix" },
        {
          name: "tableHeaders",
          type: "object",
          title: "Table Headers",
          fields: [
            { name: "product", type: "string", title: "Product" },
            { name: "grade", type: "string", title: "Grade" },
            { name: "packFormat", type: "string", title: "Pack Format" },
            { name: "quantity", type: "string", title: "Quantity" },
            { name: "moq", type: "string", title: "MOQ" },
            { name: "notes", type: "string", title: "Notes" },
          ],
        },
        { name: "footerText1", type: "string", title: "Footer Text 1" },
        { name: "footerText2", type: "string", title: "Footer Text 2" },
        {
          name: "styling",
          type: "object",
          title: "PDF Styling",
          fields: [
            { name: "fontFamily", type: "string", title: "Font Family" },
            { name: "fontStyleNormal", type: "string", title: "Font Style: Normal" },
            { name: "fontStyleBold", type: "string", title: "Font Style: Bold" },
            { name: "tableTheme", type: "string", title: "Table Theme" },
            { name: "headerFontSize", type: "number", title: "Header Font Size" },
            { name: "subtitleFontSize", type: "number", title: "Subtitle Font Size" },
            { name: "bodyFontSize", type: "number", title: "Body Font Size" },
            { name: "footerFontSize", type: "number", title: "Footer Font Size" },
            { name: "tableFontSize", type: "number", title: "Table Font Size" },
            { name: "tableCellPadding", type: "number", title: "Table Cell Padding" },
            {
              name: "colors",
              type: "object",
              title: "Colors (RGB)",
              fields: [
                { name: "deepBrown", type: "string", title: "Deep Brown (e.g., 101,67,33)" },
                { name: "gray", type: "string", title: "Gray (e.g., 100,100,100)" },
                { name: "black", type: "string", title: "Black (e.g., 0,0,0)" },
                { name: "darkGray", type: "string", title: "Dark Gray (e.g., 60,60,60)" },
                { name: "gold", type: "string", title: "Gold (e.g., 201,166,107)" },
                { name: "white", type: "string", title: "White (e.g., 255,255,255)" },
                { name: "lightGray", type: "string", title: "Light Gray (e.g., 150,150,150)" },
              ],
            },
            {
              name: "columnWidths",
              type: "object",
              title: "Table Column Widths",
              fields: [
                { name: "index", type: "number", title: "Index Column" },
                { name: "product", type: "number", title: "Product Column" },
                { name: "grade", type: "number", title: "Grade Column" },
                { name: "packFormat", type: "number", title: "Pack Format Column" },
                { name: "quantity", type: "number", title: "Quantity Column" },
                { name: "moq", type: "number", title: "MOQ Column" },
                { name: "notes", type: "number", title: "Notes Column" },
              ],
            },
          ],
        },
      ],
    }),
  ],
});
